"""auto update

Revision ID: 14eb48a69b23
Revises: 6d3af48e24eb
Create Date: 2026-07-17 09:00:25.384567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14eb48a69b23'
down_revision: Union[str, Sequence[str], None] = '6d3af48e24eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='YER', nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=True),
    sa.Column('verified_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_verifications_id'), 'payment_verifications', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('price_yer', sa.Float(), nullable=True),
    sa.Column('price_sar', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('order_reference', sa.String(length=255), nullable=False),
    sa.Column('origin_governorate', sa.String(length=100), nullable=False),
    sa.Column('destination_governorate', sa.String(length=100), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='in_transit', nullable=True),
    sa.Column('estimated_days', sa.Integer(), server_default='3', nullable=True),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('shipping_cost_yer', sa.Float(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_verifications_id'), table_name='payment_verifications')
    op.drop_table('payment_verifications')
    # ### end Alembic commands ###